name = "Another Edition"
author = "thePlaceholder"
version = "0.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b84ab0c973869807817434f10789080c302959709d2640e06c81d05e2818df92"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
datapack-folder = "global_packs/required_data"
