name = "Another Edition"
author = "thePlaceholder"
version = "0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3fc2f4941bd731c59c5d76ddf6579c339e41b3e99a09869897fa97cb6bf104a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
datapack-folder = "global_packs/required_data"
