ServerEvents.recipes(event => {
    event.remove({output: '#c:shulker_boxes'})
    event.remove({output: 'minecraft:end_stone_bricks'})
    event.remove({output: 'minecraft:end_stone_brick_stairs'})
    event.remove({output: 'minecraft:end_stone_brick_slab'})
    event.remove({output: 'minecraft:end_rod'})
    event.remove({output: 'minecraft:end_stone_brick_wall'})
    event.remove({output: 'minecraft:end_crystal'})
    event.remove({output: 'minecraft:ender_chest'})
    event.remove({output: 'minecraft:ender_eye'})
    event.remove({output: 'minecraft:purpur_slab'})
    event.remove({output: 'minecraft:purpur_stairs'})
    event.remove({output: 'minecraft:purpur_slab'})
    event.remove({output: 'minecraft:purpur_pillar'})
    event.remove({output: 'minecraft:purpur_block'})
    event.remove({output: 'minecraft:chorus_plant'})
    event.remove({output: 'minecraft:chorus_flower'})
    event.remove({output: 'minecraft:chorus_fruit'})
    event.remove({output: 'minecraft:eye_armor_trim_smithing_template'})
    event.remove({output: 'minecraft:spire_armor_trim_smithing_template'})

    event.remove({input: 'minecraft:eye_armor_trim_smithing_template'})
    event.remove({input: 'minecraft:spire_armor_trim_smithing_template'})
})