# Visit https://github.com/gizmo-ds/key-binding-hider-mod for detailed configuration options.

# Set the key bindings to unknown
SetKeyBindingToUnknown = true

# List of key bindings to hide
KeyBindings = [
    "key.advancements", 
    "key.modernfix.config",
    "key.waila.config",
    "key.waila.toggle_liquid",
    "placebo.toggleTrails",
    "placebo.toggleWings",
    "key.kubejs.kubedex",
    "key.jei.toggleCheatMode",
    "key.jei.cheatOneItem",
    "key.jei.cheatOneItem2",
    "key.jei.cheatItemStack",
    "key.jei.cheatItemStack2",
    "key.jei.copy.recipe.id",
    "gui.jei.editMode.description",
    "gui.jei.editMode.description.hide",
    "gui.jei.editMode.description.hide.wild",
    "key.jei.toggleCheatModeConfigButton",
    "key.toastcontrol.clear",
    "iris.keybind.wireframe",
    "key.curios.open.desc"
]
