# Visit https://github.com/gizmo-ds/key-binding-hider-mod for detailed configuration options.

# Set the key bindings to unknown
SetKeyBindingToUnknown = true

# List of key bindings to hide
KeyBindings = [
    "key.advancements", 
    "key.modernfix.config",
    "key.jade.narrate",
    "key.jade.config",
    "placebo.toggleTrails",
    "placebo.toggleWings",
    "key.kubejs.kubedex",
    "key.jei.toggleCheatMode",
    "key.jei.cheatOneItem",
    "key.jei.cheatOneItem2",
    "key.jei.cheatItemStack",
    "key.jei.cheatItemStack2",
    "key.jei.copy.recipe.id",
    "key.jei.toggleEditMode",
    "key.jei.toggleWildcardHideIngredient",
    "key.jei.toggleEditMode",
    "key.jei.toggleCheatModeConfigButton",
    "key.toastcontrol.clear",
    "iris.keybind.wireframe",
    "key.curios.open.desc",
    "key.jade.show_overlay"
]
