modLoader = "javafml"
loaderVersion = "[4,)"
license = "CC-BY-NC-SA-4.0"

[[mods]]
modId = "another_edition"
version = "${version}"
displayName = "Another Edition - Core"
authors = "thePlaceholder"
description = '''
The core mod for the "Minecraft: Another Edition" Modpack.
'''
#logoFile = ""

[[dependencies.another_edition]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.another_edition]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "another_edition.mixins.json"
